spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d9217amgvqtc7393ub3g-a.oregon-postgres.render.com:5432/laddukadai_db
spring.datasource.username=laddukadai_db_user
spring.datasource.password=V2Bt4JozYVICiPe7WSB7w6WwUBDvXgRY
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=laddukadai-super-secret-key-2026-pratap-cognizant
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=laddukadaicom@gmail.com
spring.mail.password=ixpocnqnppxombkx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:4200